basePath: /api/v1
definitions:
  main.tmp:
    properties:
      id:
        type: integer
    type: object
info:
  contact:
    email: martin7.heinz@gmail.com
    name: API Support
  description: Swagger API for Golang Project Blueprint.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Blueprint Swagger API
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: get user by ID
      operationId: get-user-by-int
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.tmp'
      summary: Show a account
swagger: "2.0"
