// Code generated by MockGen. DO NOT EDIT.
// Source: UseCase.go

// Package mock_UseCase is a generated GoMock package.
package mock_UseCase

import (
	fileService "Mailer/FileService/proto"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// SaveFiles mocks base method
func (m *MockInterface) SaveFiles(arg0 *fileService.Files) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFiles", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFiles indicates an expected call of SaveFiles
func (mr *MockInterfaceMockRecorder) SaveFiles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFiles", reflect.TypeOf((*MockInterface)(nil).SaveFiles), arg0)
}

// SaveAvatar mocks base method
func (m *MockInterface) SaveAvatar(arg0 *fileService.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAvatar", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAvatar indicates an expected call of SaveAvatar
func (mr *MockInterfaceMockRecorder) SaveAvatar(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAvatar", reflect.TypeOf((*MockInterface)(nil).SaveAvatar), arg0)
}

// GetAvatar mocks base method
func (m *MockInterface) GetAvatar(user *fileService.User) (*fileService.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar", user)
	ret0, _ := ret[0].(*fileService.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatar indicates an expected call of GetAvatar
func (mr *MockInterfaceMockRecorder) GetAvatar(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockInterface)(nil).GetAvatar), user)
}

// GetFiles mocks base method
func (m *MockInterface) GetFiles(id *fileService.LetterId) (*fileService.Files, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiles", id)
	ret0, _ := ret[0].(*fileService.Files)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiles indicates an expected call of GetFiles
func (mr *MockInterfaceMockRecorder) GetFiles(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiles", reflect.TypeOf((*MockInterface)(nil).GetFiles), id)
}
