// Code generated by MockGen. DO NOT EDIT.
// Source: ./DataBaseRequests.go

// Package mock_LetterRepository is a generated GoMock package.
package mock_LetterRepository

import (
	LetterModel "MainApplication/internal/Letter/LetterModel"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLetterDB is a mock of LetterDB interface
type MockLetterDB struct {
	ctrl     *gomock.Controller
	recorder *MockLetterDBMockRecorder
}

// MockLetterDBMockRecorder is the mock recorder for MockLetterDB
type MockLetterDBMockRecorder struct {
	mock *MockLetterDB
}

// NewMockLetterDB creates a new mock instance
func NewMockLetterDB(ctrl *gomock.Controller) *MockLetterDB {
	mock := &MockLetterDB{ctrl: ctrl}
	mock.recorder = &MockLetterDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLetterDB) EXPECT() *MockLetterDBMockRecorder {
	return m.recorder
}

// SaveMail mocks base method
func (m *MockLetterDB) SaveMail(arg0 LetterModel.Letter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMail indicates an expected call of SaveMail
func (mr *MockLetterDBMockRecorder) SaveMail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMail", reflect.TypeOf((*MockLetterDB)(nil).SaveMail), arg0)
}

// GetReceivedLetters mocks base method
func (m *MockLetterDB) GetReceivedLetters(arg0 string) (error, []LetterModel.Letter) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceivedLetters", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].([]LetterModel.Letter)
	return ret0, ret1
}

// GetReceivedLetters indicates an expected call of GetReceivedLetters
func (mr *MockLetterDBMockRecorder) GetReceivedLetters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivedLetters", reflect.TypeOf((*MockLetterDB)(nil).GetReceivedLetters), arg0)
}

// GetSendedLetters mocks base method
func (m *MockLetterDB) GetSendedLetters(arg0 string) (error, []LetterModel.Letter) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSendedLetters", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].([]LetterModel.Letter)
	return ret0, ret1
}

// GetSendedLetters indicates an expected call of GetSendedLetters
func (mr *MockLetterDBMockRecorder) GetSendedLetters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSendedLetters", reflect.TypeOf((*MockLetterDB)(nil).GetSendedLetters), arg0)
}

// GetReceivedLettersDir mocks base method
func (m *MockLetterDB) GetReceivedLettersDir(arg0 uint64) (error, []LetterModel.Letter) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceivedLettersDir", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].([]LetterModel.Letter)
	return ret0, ret1
}

// GetReceivedLettersDir indicates an expected call of GetReceivedLettersDir
func (mr *MockLetterDBMockRecorder) GetReceivedLettersDir(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceivedLettersDir", reflect.TypeOf((*MockLetterDB)(nil).GetReceivedLettersDir), arg0)
}

// GetSendedLettersDir mocks base method
func (m *MockLetterDB) GetSendedLettersDir(arg0 uint64) (error, []LetterModel.Letter) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSendedLettersDir", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].([]LetterModel.Letter)
	return ret0, ret1
}

// GetSendedLettersDir indicates an expected call of GetSendedLettersDir
func (mr *MockLetterDBMockRecorder) GetSendedLettersDir(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSendedLettersDir", reflect.TypeOf((*MockLetterDB)(nil).GetSendedLettersDir), arg0)
}

// WatchLetter mocks base method
func (m *MockLetterDB) WatchLetter(arg0 uint64) (error, LetterModel.Letter) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchLetter", arg0)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].(LetterModel.Letter)
	return ret0, ret1
}

// WatchLetter indicates an expected call of WatchLetter
func (mr *MockLetterDBMockRecorder) WatchLetter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchLetter", reflect.TypeOf((*MockLetterDB)(nil).WatchLetter), arg0)
}
