// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: SmtpService/proto/smtp/smtp.proto

// protoc --go_out=plugins=grpc:. *.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Letter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lid      uint64 `protobuf:"varint,1,opt,name=lid,proto3" json:"lid,omitempty"`
	Sender   string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Theme    string `protobuf:"bytes,4,opt,name=theme,proto3" json:"theme,omitempty"`
	Text     string `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	DateTime uint64 `protobuf:"varint,6,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
}

func (x *Letter) Reset() {
	*x = Letter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SmtpService_proto_smtp_smtp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Letter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Letter) ProtoMessage() {}

func (x *Letter) ProtoReflect() protoreflect.Message {
	mi := &file_SmtpService_proto_smtp_smtp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Letter.ProtoReflect.Descriptor instead.
func (*Letter) Descriptor() ([]byte, []int) {
	return file_SmtpService_proto_smtp_smtp_proto_rawDescGZIP(), []int{0}
}

func (x *Letter) GetLid() uint64 {
	if x != nil {
		return x.Lid
	}
	return 0
}

func (x *Letter) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Letter) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Letter) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Letter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Letter) GetDateTime() uint64 {
	if x != nil {
		return x.DateTime
	}
	return 0
}

type DirName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DirName string `protobuf:"bytes,1,opt,name=dirName,proto3" json:"dirName,omitempty"`
}

func (x *DirName) Reset() {
	*x = DirName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SmtpService_proto_smtp_smtp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirName) ProtoMessage() {}

func (x *DirName) ProtoReflect() protoreflect.Message {
	mi := &file_SmtpService_proto_smtp_smtp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirName.ProtoReflect.Descriptor instead.
func (*DirName) Descriptor() ([]byte, []int) {
	return file_SmtpService_proto_smtp_smtp_proto_rawDescGZIP(), []int{1}
}

func (x *DirName) GetDirName() string {
	if x != nil {
		return x.DirName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok          bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SmtpService_proto_smtp_smtp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_SmtpService_proto_smtp_smtp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_SmtpService_proto_smtp_smtp_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_SmtpService_proto_smtp_smtp_proto protoreflect.FileDescriptor

var file_SmtpService_proto_smtp_smtp_proto_rawDesc = []byte{
	0x0a, 0x21, 0x53, 0x6d, 0x74, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6d, 0x74, 0x70, 0x2f, 0x73, 0x6d, 0x74, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x06, 0x4c,
	0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x68, 0x65, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x65, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x23, 0x0a, 0x07, 0x44, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x69, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x32, 0x3d, 0x0a, 0x0d, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x74, 0x74,
	0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SmtpService_proto_smtp_smtp_proto_rawDescOnce sync.Once
	file_SmtpService_proto_smtp_smtp_proto_rawDescData = file_SmtpService_proto_smtp_smtp_proto_rawDesc
)

func file_SmtpService_proto_smtp_smtp_proto_rawDescGZIP() []byte {
	file_SmtpService_proto_smtp_smtp_proto_rawDescOnce.Do(func() {
		file_SmtpService_proto_smtp_smtp_proto_rawDescData = protoimpl.X.CompressGZIP(file_SmtpService_proto_smtp_smtp_proto_rawDescData)
	})
	return file_SmtpService_proto_smtp_smtp_proto_rawDescData
}

var file_SmtpService_proto_smtp_smtp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_SmtpService_proto_smtp_smtp_proto_goTypes = []interface{}{
	(*Letter)(nil),   // 0: proto.Letter
	(*DirName)(nil),  // 1: proto.DirName
	(*Response)(nil), // 2: proto.Response
}
var file_SmtpService_proto_smtp_smtp_proto_depIdxs = []int32{
	0, // 0: proto.LetterService.SendLetter:input_type -> proto.Letter
	2, // 1: proto.LetterService.SendLetter:output_type -> proto.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SmtpService_proto_smtp_smtp_proto_init() }
func file_SmtpService_proto_smtp_smtp_proto_init() {
	if File_SmtpService_proto_smtp_smtp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SmtpService_proto_smtp_smtp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Letter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SmtpService_proto_smtp_smtp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_SmtpService_proto_smtp_smtp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SmtpService_proto_smtp_smtp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_SmtpService_proto_smtp_smtp_proto_goTypes,
		DependencyIndexes: file_SmtpService_proto_smtp_smtp_proto_depIdxs,
		MessageInfos:      file_SmtpService_proto_smtp_smtp_proto_msgTypes,
	}.Build()
	File_SmtpService_proto_smtp_smtp_proto = out.File
	file_SmtpService_proto_smtp_smtp_proto_rawDesc = nil
	file_SmtpService_proto_smtp_smtp_proto_goTypes = nil
	file_SmtpService_proto_smtp_smtp_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LetterServiceClient is the client API for LetterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LetterServiceClient interface {
	SendLetter(ctx context.Context, in *Letter, opts ...grpc.CallOption) (*Response, error)
}

type letterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLetterServiceClient(cc grpc.ClientConnInterface) LetterServiceClient {
	return &letterServiceClient{cc}
}

func (c *letterServiceClient) SendLetter(ctx context.Context, in *Letter, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.LetterService/SendLetter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LetterServiceServer is the server API for LetterService service.
type LetterServiceServer interface {
	SendLetter(context.Context, *Letter) (*Response, error)
}

// UnimplementedLetterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLetterServiceServer struct {
}

func (*UnimplementedLetterServiceServer) SendLetter(context.Context, *Letter) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLetter not implemented")
}

func RegisterLetterServiceServer(s *grpc.Server, srv LetterServiceServer) {
	s.RegisterService(&_LetterService_serviceDesc, srv)
}

func _LetterService_SendLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Letter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LetterServiceServer).SendLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LetterService/SendLetter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LetterServiceServer).SendLetter(ctx, req.(*Letter))
	}
	return interceptor(ctx, in, info, handler)
}

var _LetterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LetterService",
	HandlerType: (*LetterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLetter",
			Handler:    _LetterService_SendLetter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "SmtpService/proto/smtp/smtp.proto",
}
