// Code generated by MockGen. DO NOT EDIT.
// Source: ./LetterDelivery.go

// Package mock_Delivery is a generated GoMock package.
package mock_Delivery

import (
	gomock "github.com/golang/mock/gomock"
)
