// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package LetterModel

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson69af0b64DecodeMainApplicationInternalLetterLetterModel(in *jlexer.Lexer, out *Letter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Id":
			out.Id = uint64(in.Uint64())
		case "Sender":
			out.Sender = string(in.String())
		case "Receiver":
			out.Receiver = string(in.String())
		case "Theme":
			out.Theme = string(in.String())
		case "Text":
			out.Text = string(in.String())
		case "DateTime":
			out.DateTime = int64(in.Int64())
		case "IsWatched":
			out.IsWatched = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson69af0b64EncodeMainApplicationInternalLetterLetterModel(out *jwriter.Writer, in Letter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Id))
	}
	{
		const prefix string = ",\"Sender\":"
		out.RawString(prefix)
		out.String(string(in.Sender))
	}
	{
		const prefix string = ",\"Receiver\":"
		out.RawString(prefix)
		out.String(string(in.Receiver))
	}
	{
		const prefix string = ",\"Theme\":"
		out.RawString(prefix)
		out.String(string(in.Theme))
	}
	{
		const prefix string = ",\"Text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	{
		const prefix string = ",\"DateTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.DateTime))
	}
	{
		const prefix string = ",\"IsWatched\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsWatched))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Letter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson69af0b64EncodeMainApplicationInternalLetterLetterModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Letter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson69af0b64EncodeMainApplicationInternalLetterLetterModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Letter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson69af0b64DecodeMainApplicationInternalLetterLetterModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Letter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson69af0b64DecodeMainApplicationInternalLetterLetterModel(l, v)
}
